# Generated by Django 3.2.9 on 2021-11-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory_type',
            new_name='inventory',
        ),
    ]
